import { Router } from 'express';
import { roleRoutes } from './roleRoutes';
import { authRoutes } from './authRoutes';
import { webAuthRoutes } from './webAuthRoutes';
import { fileUploadRoutes } from './fileUploadRoutes';
import { deviceRoutes } from './deviceRoutes';
import { userRoutes } from './userRoutes';
import { addressRoutes } from './addressRoutes';
import { productRoutes } from './productRoutes';
import { productVariantRoutes } from './productVariantRoutes';
import { productReviewRoutes } from './productReviewRoutes';
import { wishlistRoutes } from './wishlistRoutes';
import { cartRoutes } from './cartRoutes';
import { cartItemRoutes } from './cartItemRoutes';
import { orderRoutes } from './orderRoutes';
import { orderItemRoutes } from './orderItemRoutes';
import { orderTrackingRoutes } from './orderTrackingRoutes';
import { notificationRoutes } from './notificationRoutes';
import { couponRoutes } from './couponRoutes';
import { bannerRoutes } from './bannerRoutes';
import { supportTicketRoutes } from './supportTicketRoutes';
import { auditLogRoutes } from './auditLogRoutes';
import { settingRoutes } from './settingRoutes';
import { otpRoutes } from './otpRoutes';
import { categoryAdminRoutes } from './categoryAdminRoutes';
import { deliveryRoutes } from './deliveryRoutes';

const router = Router();

router.use('/roles', roleRoutes);
router.use('/auth', authRoutes);
router.use('/web-auth', webAuthRoutes);
router.use('/uploads', fileUploadRoutes);
router.use('/devices', deviceRoutes);
router.use('/users', userRoutes);
router.use('/addresses', addressRoutes);
router.use('/products', productRoutes);
router.use('/product-variants', productVariantRoutes);
router.use('/product-reviews', productReviewRoutes);
router.use('/wishlists', wishlistRoutes);
router.use('/carts', cartRoutes);
router.use('/cart-items', cartItemRoutes);
router.use('/orders', orderRoutes);
router.use('/order-items', orderItemRoutes);
router.use('/order-tracking', orderTrackingRoutes);
router.use('/notifications', notificationRoutes);
router.use('/coupons', couponRoutes);
router.use('/banners', bannerRoutes);
router.use('/support-tickets', supportTicketRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/settings', settingRoutes);
router.use('/', otpRoutes);
router.use('/department-admins', categoryAdminRoutes);
router.use('/delivery-users', deliveryRoutes);

export { router as apiRouter };
