import { Router } from 'express';
import { roleRoutes } from './roleRoutes.ts';
import { authRoutes } from './authRoutes.ts';
import { fileUploadRoutes } from './fileUploadRoutes.ts';
import { deviceRoutes } from './deviceRoutes.ts';
import { userRoutes } from './userRoutes.ts';
import { addressRoutes } from './addressRoutes.ts';
import { categoryRoutes } from './categoryRoutes.ts';
import { subCategoryRoutes } from './subCategoryRoutes.ts';
import { productRoutes } from './productRoutes.ts';
import { productVariantRoutes } from './productVariantRoutes.ts';
import { productReviewRoutes } from './productReviewRoutes.ts';
import { wishlistRoutes } from './wishlistRoutes.ts';
import { cartRoutes } from './cartRoutes.ts';
import { cartItemRoutes } from './cartItemRoutes.ts';
import { orderRoutes } from './orderRoutes.ts';
import { orderItemRoutes } from './orderItemRoutes.ts';
import { orderTrackingRoutes } from './orderTrackingRoutes.ts';
import { notificationRoutes } from './notificationRoutes.ts';
import { couponRoutes } from './couponRoutes.ts';
import { bannerRoutes } from './bannerRoutes.ts';
import { supportTicketRoutes } from './supportTicketRoutes.ts';
import { auditLogRoutes } from './auditLogRoutes.ts';
import { settingRoutes } from './settingRoutes.ts';

const router = Router();

router.use('/roles', roleRoutes);
router.use('/auth', authRoutes);
router.use('/uploads', fileUploadRoutes);
router.use('/devices', deviceRoutes);
router.use('/users', userRoutes);
router.use('/addresses', addressRoutes);
router.use('/categories', categoryRoutes);
router.use('/subcategories', subCategoryRoutes);
router.use('/products', productRoutes);
router.use('/product-variants', productVariantRoutes);
router.use('/product-reviews', productReviewRoutes);
router.use('/wishlists', wishlistRoutes);
router.use('/carts', cartRoutes);
router.use('/cart-items', cartItemRoutes);
router.use('/orders', orderRoutes);
router.use('/order-items', orderItemRoutes);
router.use('/order-tracking', orderTrackingRoutes);
router.use('/notifications', notificationRoutes);
router.use('/coupons', couponRoutes);
router.use('/banners', bannerRoutes);
router.use('/support-tickets', supportTicketRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/settings', settingRoutes);

export { router as apiRouter };
