export const schemas: Record<string, object> = {
  Pagination: {
    type: 'object',
    properties: {
      page: { type: 'integer', example: 1 },
      limit: { type: 'integer', example: 10 },
      total: { type: 'integer', example: 100 },
      totalPages: { type: 'integer', example: 10 },
      hasNextPage: { type: 'boolean', example: true },
      hasPrevPage: { type: 'boolean', example: false },
    },
  },

  ApiSuccessResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string', example: 'Success' },
      data: { type: 'object' },
    },
  },

  ApiErrorResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: false },
      message: { type: 'string', example: 'Error message' },
      code: { type: 'string', example: 'VALIDATION_ERROR' },
      errors: { type: 'object' },
    },
  },

  User: {
    type: 'object',
    properties: {
      id: { type: 'string', description: 'UUID primary key' },
      email: { type: 'string', format: 'email', maxLength: 254, example: 'user@example.com' },
      phone: { type: 'string', maxLength: 20, nullable: true },
      firstName: { type: 'string', maxLength: 64, example: 'John' },
      lastName: { type: 'string', maxLength: 64, example: 'Doe' },
      avatar: { type: 'string', nullable: true },
      roleId: { type: 'string', description: 'Role UUID reference' },
      status: { type: 'string', enum: ['ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION'] },
      emailVerified: { type: 'boolean' },
      phoneVerified: { type: 'boolean' },
      lastLoginAt: { type: 'string', format: 'date-time', nullable: true },
      vendorId: { type: 'string', nullable: true },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['email', 'passwordHash', 'roleId', 'firstName', 'lastName'],
  },

  CreateUserDto: {
    type: 'object',
    required: ['email', 'password', 'firstName', 'lastName', 'roleId'],
    properties: {
      email: { type: 'string', format: 'email', maxLength: 254, example: 'user@example.com' },
      password: { type: 'string', minLength: 6, example: 'securePassword123' },
      firstName: { type: 'string', maxLength: 64, example: 'John' },
      lastName: { type: 'string', maxLength: 64, example: 'Doe' },
      phone: { type: 'string', maxLength: 20, example: '+1234567890' },
      roleId: { type: 'string', description: 'Role UUID' },
      status: { type: 'string', enum: ['ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION'] },
    },
  },

  UpdateUserDto: {
    type: 'object',
    properties: {
      email: { type: 'string', format: 'email', maxLength: 254 },
      firstName: { type: 'string', maxLength: 64 },
      lastName: { type: 'string', maxLength: 64 },
      phone: { type: 'string', maxLength: 20 },
      avatar: { type: 'string' },
      status: { type: 'string', enum: ['ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION'] },
    },
  },

  CreateRoleDto: {
    type: 'object',
    required: ['name', 'displayName'],
    properties: {
      name: { type: 'string', enum: ['USER', 'ADMIN', 'SUPER_ADMIN', 'DELIVERY'] },
      displayName: { type: 'string', maxLength: 64, example: 'Regular User' },
      description: { type: 'string', maxLength: 500 },
      permissions: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            resource: { type: 'string', maxLength: 64, example: 'users' },
            actions: { type: 'array', items: { type: 'string' }, example: ['create', 'read', 'update', 'delete'] },
          },
        },
      },
      isSystemRole: { type: 'boolean' },
      isActive: { type: 'boolean' },
    },
  },

  Role: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      name: { type: 'string', enum: ['USER', 'ADMIN', 'SUPER_ADMIN', 'DELIVERY'] },
      displayName: { type: 'string' },
      description: { type: 'string' },
      permissions: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            resource: { type: 'string' },
            actions: { type: 'array', items: { type: 'string' } },
          },
        },
      },
      isSystemRole: { type: 'boolean' },
      isActive: { type: 'boolean' },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },

  Category: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      name: { type: 'string', maxLength: 120, example: 'Electronics' },
      slug: { type: 'string', maxLength: 140, example: 'electronics' },
      description: { type: 'string', maxLength: 2000 },
      image: { type: 'string', nullable: true },
      icon: { type: 'string', nullable: true },
      sortOrder: { type: 'integer', example: 0 },
      isActive: { type: 'boolean' },
      vendorId: { type: 'string', nullable: true },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['name', 'slug'],
  },

  CreateCategoryDto: {
    type: 'object',
    required: ['name', 'slug'],
    properties: {
      name: { type: 'string', maxLength: 120, example: 'Electronics' },
      slug: { type: 'string', maxLength: 140, example: 'electronics', pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$' },
      description: { type: 'string', maxLength: 2000 },
      image: { type: 'string' },
      icon: { type: 'string' },
      sortOrder: { type: 'integer' },
      isActive: { type: 'boolean' },
    },
  },

  SubCategory: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      categoryId: { type: 'string', description: 'Parent Category UUID' },
      name: { type: 'string', maxLength: 120, example: 'Smartphones' },
      slug: { type: 'string', maxLength: 140, example: 'smartphones' },
      description: { type: 'string', maxLength: 2000 },
      image: { type: 'string', nullable: true },
      sortOrder: { type: 'integer' },
      isActive: { type: 'boolean' },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['categoryId', 'name', 'slug'],
  },

  CreateSubCategoryDto: {
    type: 'object',
    required: ['categoryId', 'name', 'slug'],
    properties: {
      categoryId: { type: 'string', description: 'Category UUID' },
      name: { type: 'string', maxLength: 120, example: 'Smartphones' },
      slug: { type: 'string', maxLength: 140, example: 'smartphones', pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$' },
      description: { type: 'string', maxLength: 2000 },
      image: { type: 'string' },
      sortOrder: { type: 'integer' },
      isActive: { type: 'boolean' },
    },
  },

  Product: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      categoryId: { type: 'string' },
      subCategoryId: { type: 'string' },
      vendorId: { type: 'string', nullable: true },
      name: { type: 'string', maxLength: 200, example: 'Wireless Headphones' },
      slug: { type: 'string', maxLength: 220, example: 'wireless-headphones' },
      description: { type: 'string', maxLength: 10000 },
      shortDescription: { type: 'string', maxLength: 500 },
      brand: { type: 'string', maxLength: 100, nullable: true },
      tags: { type: 'array', items: { type: 'string' }, maxItems: 50 },
      images: { type: 'array', items: { type: 'string' }, maxItems: 20 },
      thumbnail: { type: 'string', nullable: true },
      priceRange: {
        type: 'object',
        properties: {
          min: { type: 'number', minimum: 0 },
          max: { type: 'number', minimum: 0 },
          currency: { type: 'string', maxLength: 3, example: 'USD' },
        },
      },
      attributes: { type: 'object', additionalProperties: { type: 'string' } },
      status: { type: 'string', enum: ['DRAFT', 'PUBLISHED', 'ARCHIVED'] },
      isFeatured: { type: 'boolean' },
      rating: {
        type: 'object',
        properties: {
          average: { type: 'number', minimum: 0, maximum: 5 },
          count: { type: 'integer', minimum: 0 },
          distribution: {
            type: 'object',
            properties: {
              one: { type: 'integer' }, two: { type: 'integer' },
              three: { type: 'integer' }, four: { type: 'integer' },
              five: { type: 'integer' },
            },
          },
        },
      },
      totalSold: { type: 'integer', minimum: 0 },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['categoryId', 'subCategoryId', 'name', 'slug', 'description', 'priceRange'],
  },

  CreateProductDto: {
    type: 'object',
    required: ['categoryId', 'subCategoryId', 'name', 'slug', 'description', 'priceRange'],
    properties: {
      categoryId: { type: 'string' },
      subCategoryId: { type: 'string' },
      name: { type: 'string', maxLength: 200, example: 'Wireless Headphones' },
      slug: { type: 'string', maxLength: 220, example: 'wireless-headphones' },
      description: { type: 'string', maxLength: 10000 },
      shortDescription: { type: 'string', maxLength: 500 },
      brand: { type: 'string', maxLength: 100 },
      tags: { type: 'array', items: { type: 'string' }, maxItems: 50 },
      images: { type: 'array', items: { type: 'string' }, maxItems: 20 },
      thumbnail: { type: 'string' },
      priceRange: {
        type: 'object',
        required: ['min', 'max', 'currency'],
        properties: {
          min: { type: 'number', minimum: 0, example: 99.99 },
          max: { type: 'number', minimum: 0, example: 149.99 },
          currency: { type: 'string', maxLength: 3, example: 'USD' },
        },
      },
      attributes: { type: 'object', additionalProperties: { type: 'string' } },
      status: { type: 'string', enum: ['DRAFT', 'PUBLISHED', 'ARCHIVED'] },
      isFeatured: { type: 'boolean' },
    },
  },

  ProductVariant: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      productId: { type: 'string' },
      vendorId: { type: 'string', nullable: true },
      sku: { type: 'string', maxLength: 64, example: 'WH-BLACK-M' },
      name: { type: 'string', maxLength: 200, example: 'Black / Medium' },
      attributes: { type: 'object', additionalProperties: { type: 'string' } },
      price: { type: 'number', minimum: 0, example: 129.99 },
      compareAtPrice: { type: 'number', minimum: 0, nullable: true },
      costPrice: { type: 'number', minimum: 0, nullable: true },
      currency: { type: 'string', maxLength: 3 },
      inventory: {
        type: 'object',
        properties: {
          quantity: { type: 'integer', minimum: 0 },
          reserved: { type: 'integer', minimum: 0 },
          lowStockThreshold: { type: 'integer', minimum: 0 },
        },
      },
      weight: { type: 'number', nullable: true },
      images: { type: 'array', items: { type: 'string' } },
      barcode: { type: 'string', nullable: true },
      isDefault: { type: 'boolean' },
      isActive: { type: 'boolean' },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['productId', 'sku', 'name', 'price', 'inventory'],
  },

  CreateProductVariantDto: {
    type: 'object',
    required: ['productId', 'sku', 'name', 'price', 'inventory'],
    properties: {
      productId: { type: 'string' },
      sku: { type: 'string', maxLength: 64, example: 'WH-BLACK-M' },
      name: { type: 'string', maxLength: 200, example: 'Black / Medium' },
      attributes: { type: 'object', additionalProperties: { type: 'string' } },
      price: { type: 'number', minimum: 0, example: 129.99 },
      compareAtPrice: { type: 'number', minimum: 0 },
      costPrice: { type: 'number', minimum: 0 },
      currency: { type: 'string', maxLength: 3 },
      inventory: {
        type: 'object',
        required: ['quantity'],
        properties: {
          quantity: { type: 'integer', minimum: 0, example: 100 },
          reserved: { type: 'integer', minimum: 0 },
          lowStockThreshold: { type: 'integer', minimum: 0, example: 5 },
        },
      },
      weight: { type: 'number' },
      images: { type: 'array', items: { type: 'string' } },
      barcode: { type: 'string' },
      isDefault: { type: 'boolean' },
      isActive: { type: 'boolean' },
    },
  },

  ProductReview: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      productId: { type: 'string' },
      userId: { type: 'string' },
      orderId: { type: 'string', nullable: true },
      variantId: { type: 'string', nullable: true },
      rating: { type: 'integer', minimum: 1, maximum: 5, example: 4 },
      title: { type: 'string', maxLength: 200 },
      comment: { type: 'string', maxLength: 5000, example: 'Great product!' },
      images: { type: 'array', items: { type: 'string' }, maxItems: 5 },
      isVerifiedPurchase: { type: 'boolean' },
      isApproved: { type: 'boolean' },
      isHidden: { type: 'boolean' },
      helpfulCount: { type: 'integer', minimum: 0 },
      adminResponse: {
        type: 'object',
        nullable: true,
        properties: {
          message: { type: 'string' },
          respondedBy: { type: 'string' },
          respondedAt: { type: 'string', format: 'date-time' },
        },
      },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['productId', 'userId', 'rating', 'comment'],
  },

  CreateProductReviewDto: {
    type: 'object',
    required: ['productId', 'rating', 'comment'],
    properties: {
      productId: { type: 'string' },
      variantId: { type: 'string' },
      orderId: { type: 'string' },
      rating: { type: 'integer', minimum: 1, maximum: 5, example: 4 },
      title: { type: 'string', maxLength: 200 },
      comment: { type: 'string', maxLength: 5000, example: 'Great product!' },
      images: { type: 'array', items: { type: 'string' }, maxItems: 5 },
    },
  },

  Order: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      orderNumber: { type: 'string', maxLength: 32, example: 'ORD-001' },
      userId: { type: 'string' },
      status: {
        type: 'string',
        enum: ['PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURNED', 'REFUNDED'],
      },
      payment: {
        type: 'object',
        properties: {
          method: { type: 'string', enum: ['COD', 'STRIPE', 'PAYPAL', 'RAZORPAY'] },
          status: { type: 'string', enum: ['PENDING', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED', 'CANCELLED'] },
          transactionId: { type: 'string', nullable: true },
          paidAt: { type: 'string', format: 'date-time', nullable: true },
          refundAmount: { type: 'number', minimum: 0 },
        },
      },
      shippingAddress: { type: 'object' },
      billingAddress: { type: 'object', nullable: true },
      pricing: {
        type: 'object',
        properties: {
          subtotal: { type: 'number', minimum: 0 },
          discount: { type: 'number', minimum: 0 },
          shipping: { type: 'number', minimum: 0 },
          tax: { type: 'number', minimum: 0 },
          total: { type: 'number', minimum: 0 },
          currency: { type: 'string', maxLength: 3 },
        },
      },
      couponCode: { type: 'string', nullable: true },
      customerNotes: { type: 'string', maxLength: 1000 },
      isArchived: { type: 'boolean' },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['orderNumber', 'userId', 'payment', 'shippingAddress', 'pricing'],
  },

  CreateOrderDto: {
    type: 'object',
    required: ['shippingAddress', 'payment'],
    properties: {
      shippingAddress: {
        type: 'object',
        required: ['fullName', 'phone', 'addressLine1', 'city', 'state', 'country', 'postalCode'],
        properties: {
          fullName: { type: 'string', example: 'John Doe' },
          phone: { type: 'string', example: '+1234567890' },
          addressLine1: { type: 'string', example: '123 Main St' },
          addressLine2: { type: 'string' },
          city: { type: 'string', example: 'New York' },
          state: { type: 'string', example: 'NY' },
          country: { type: 'string', example: 'US' },
          postalCode: { type: 'string', example: '10001' },
        },
      },
      billingAddress: { type: 'object' },
      payment: {
        type: 'object',
        required: ['method'],
        properties: {
          method: { type: 'string', enum: ['COD', 'STRIPE', 'PAYPAL', 'RAZORPAY'], example: 'COD' },
          transactionId: { type: 'string' },
        },
      },
      couponCode: { type: 'string' },
      customerNotes: { type: 'string', maxLength: 1000 },
    },
  },

  OrderItem: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      orderId: { type: 'string' },
      productId: { type: 'string' },
      variantId: { type: 'string' },
      sku: { type: 'string', example: 'WH-BLACK-M' },
      productName: { type: 'string', example: 'Wireless Headphones' },
      variantName: { type: 'string', example: 'Black / Medium' },
      thumbnail: { type: 'string', nullable: true },
      quantity: { type: 'integer', minimum: 1, example: 2 },
      unitPrice: { type: 'number', minimum: 0, example: 129.99 },
      discount: { type: 'number', minimum: 0 },
      tax: { type: 'number', minimum: 0 },
      lineTotal: { type: 'number', minimum: 0 },
      currency: { type: 'string', maxLength: 3 },
      status: {
        type: 'string',
        enum: ['PENDING', 'CONFIRMED', 'PICKED', 'PACKED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED'],
      },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['orderId', 'productId', 'variantId', 'sku', 'productName', 'variantName', 'quantity', 'unitPrice', 'lineTotal'],
  },

  OrderTracking: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      orderId: { type: 'string' },
      status: { type: 'string', enum: ['PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURNED', 'REFUNDED'] },
      title: { type: 'string', maxLength: 200, example: 'Order Confirmed' },
      message: { type: 'string', maxLength: 2000 },
      location: {
        type: 'object',
        nullable: true,
        properties: {
          type: { type: 'string', enum: ['Point'] },
          coordinates: { type: 'array', items: { type: 'number' }, minItems: 2, maxItems: 2 },
        },
      },
      locationLabel: { type: 'string', maxLength: 200 },
      source: { type: 'string', enum: ['SYSTEM', 'ADMIN', 'DELIVERY', 'CUSTOMER'] },
      metadata: { type: 'object' },
      createdAt: { type: 'string', format: 'date-time' },
    },
    required: ['orderId', 'status', 'title'],
  },

  Cart: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      userId: { type: 'string', nullable: true },
      sessionId: { type: 'string', nullable: true },
      status: { type: 'string', enum: ['ACTIVE', 'ABANDONED', 'CONVERTED', 'EXPIRED'] },
      couponCode: { type: 'string', nullable: true },
      currency: { type: 'string', maxLength: 3 },
      subtotal: { type: 'number', minimum: 0 },
      discount: { type: 'number', minimum: 0 },
      shipping: { type: 'number', minimum: 0 },
      tax: { type: 'number', minimum: 0 },
      total: { type: 'number', minimum: 0 },
      itemCount: { type: 'integer', minimum: 0 },
      convertedOrderId: { type: 'string', nullable: true },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },

  CartItem: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      cartId: { type: 'string' },
      productId: { type: 'string' },
      variantId: { type: 'string' },
      quantity: { type: 'integer', minimum: 1, maximum: 99, example: 1 },
      unitPrice: { type: 'number', minimum: 0, example: 129.99 },
      lineTotal: { type: 'number', minimum: 0 },
      currency: { type: 'string', maxLength: 3 },
      productName: { type: 'string', maxLength: 200 },
      variantName: { type: 'string', maxLength: 200 },
      thumbnail: { type: 'string', nullable: true },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['cartId', 'productId', 'variantId', 'quantity', 'unitPrice', 'lineTotal', 'productName', 'variantName'],
  },

  CreateCartItemDto: {
    type: 'object',
    required: ['cartId', 'productId', 'variantId', 'quantity'],
    properties: {
      cartId: { type: 'string' },
      productId: { type: 'string' },
      variantId: { type: 'string' },
      quantity: { type: 'integer', minimum: 1, maximum: 99, example: 1 },
    },
  },

  Wishlist: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      userId: { type: 'string' },
      name: { type: 'string', maxLength: 100, example: 'My Wishlist' },
      isDefault: { type: 'boolean' },
      items: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            productId: { type: 'string' },
            variantId: { type: 'string', nullable: true },
            addedAt: { type: 'string', format: 'date-time' },
            note: { type: 'string', maxLength: 300 },
          },
        },
        maxItems: 500,
      },
      itemCount: { type: 'integer', minimum: 0 },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['userId'],
  },

  CreateWishlistDto: {
    type: 'object',
    properties: {
      name: { type: 'string', maxLength: 100, example: 'My Wishlist' },
      isDefault: { type: 'boolean' },
    },
  },

  Coupon: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      code: { type: 'string', maxLength: 32, example: 'SUMMER20' },
      name: { type: 'string', maxLength: 120, example: 'Summer Sale 20%' },
      description: { type: 'string', maxLength: 500 },
      type: { type: 'string', enum: ['PERCENTAGE', 'FIXED', 'FREE_SHIPPING'] },
      value: { type: 'number', minimum: 0, example: 20 },
      maxDiscount: { type: 'number', minimum: 0, nullable: true },
      minOrderAmount: { type: 'number', minimum: 0, example: 50 },
      usageLimit: { type: 'integer', minimum: 1, nullable: true },
      usageCount: { type: 'integer', minimum: 0 },
      perUserLimit: { type: 'integer', minimum: 1, example: 1 },
      applicability: { type: 'string', enum: ['ALL', 'CATEGORIES', 'PRODUCTS'] },
      startDate: { type: 'string', format: 'date-time' },
      endDate: { type: 'string', format: 'date-time' },
      isActive: { type: 'boolean' },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['code', 'name', 'type', 'value', 'startDate', 'endDate'],
  },

  CreateCouponDto: {
    type: 'object',
    required: ['code', 'name', 'type', 'value', 'startDate', 'endDate'],
    properties: {
      code: { type: 'string', maxLength: 32, example: 'SUMMER20' },
      name: { type: 'string', maxLength: 120, example: 'Summer Sale 20%' },
      description: { type: 'string', maxLength: 500 },
      type: { type: 'string', enum: ['PERCENTAGE', 'FIXED', 'FREE_SHIPPING'], example: 'PERCENTAGE' },
      value: { type: 'number', minimum: 0, example: 20 },
      maxDiscount: { type: 'number', minimum: 0 },
      minOrderAmount: { type: 'number', minimum: 0, example: 50 },
      usageLimit: { type: 'integer', minimum: 1 },
      perUserLimit: { type: 'integer', minimum: 1, example: 1 },
      applicability: { type: 'string', enum: ['ALL', 'CATEGORIES', 'PRODUCTS'] },
      applicableCategoryIds: { type: 'array', items: { type: 'string' } },
      applicableProductIds: { type: 'array', items: { type: 'string' } },
      startDate: { type: 'string', format: 'date-time' },
      endDate: { type: 'string', format: 'date-time' },
      isActive: { type: 'boolean' },
    },
  },

  Banner: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      title: { type: 'string', maxLength: 200, example: 'Summer Sale' },
      subtitle: { type: 'string', maxLength: 300 },
      image: { type: 'string', example: 'https://example.com/banner.jpg' },
      mobileImage: { type: 'string', nullable: true },
      linkType: { type: 'string', enum: ['NONE', 'PRODUCT', 'CATEGORY', 'SUBCATEGORY', 'EXTERNAL', 'COUPON'] },
      linkValue: { type: 'string', nullable: true },
      platform: { type: 'string', enum: ['ALL', 'WEB', 'ANDROID', 'IOS'] },
      position: { type: 'string', maxLength: 64, example: 'hero' },
      sortOrder: { type: 'integer' },
      startDate: { type: 'string', format: 'date-time', nullable: true },
      endDate: { type: 'string', format: 'date-time', nullable: true },
      isActive: { type: 'boolean' },
      clickCount: { type: 'integer', minimum: 0 },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['title', 'image', 'position'],
  },

  CreateBannerDto: {
    type: 'object',
    required: ['title', 'image', 'position'],
    properties: {
      title: { type: 'string', maxLength: 200, example: 'Summer Sale' },
      subtitle: { type: 'string', maxLength: 300 },
      image: { type: 'string', example: 'https://example.com/banner.jpg' },
      mobileImage: { type: 'string' },
      linkType: { type: 'string', enum: ['NONE', 'PRODUCT', 'CATEGORY', 'SUBCATEGORY', 'EXTERNAL', 'COUPON'] },
      linkValue: { type: 'string' },
      platform: { type: 'string', enum: ['ALL', 'WEB', 'ANDROID', 'IOS'] },
      position: { type: 'string', maxLength: 64, example: 'hero' },
      sortOrder: { type: 'integer' },
      startDate: { type: 'string', format: 'date-time' },
      endDate: { type: 'string', format: 'date-time' },
      isActive: { type: 'boolean' },
    },
  },

  Address: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      userId: { type: 'string' },
      label: { type: 'string', enum: ['HOME', 'WORK', 'OTHER'] },
      fullName: { type: 'string', maxLength: 120, example: 'John Doe' },
      phone: { type: 'string', maxLength: 20, example: '+1234567890' },
      addressLine1: { type: 'string', maxLength: 200, example: '123 Main St' },
      addressLine2: { type: 'string', maxLength: 200 },
      city: { type: 'string', maxLength: 100, example: 'New York' },
      state: { type: 'string', maxLength: 100, example: 'NY' },
      country: { type: 'string', maxLength: 100, example: 'US' },
      postalCode: { type: 'string', maxLength: 20, example: '10001' },
      isDefault: { type: 'boolean' },
      deliveryInstructions: { type: 'string', maxLength: 500 },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['userId', 'fullName', 'phone', 'addressLine1', 'city', 'state', 'country', 'postalCode'],
  },

  CreateAddressDto: {
    type: 'object',
    required: ['fullName', 'phone', 'addressLine1', 'city', 'state', 'country', 'postalCode'],
    properties: {
      label: { type: 'string', enum: ['HOME', 'WORK', 'OTHER'] },
      fullName: { type: 'string', maxLength: 120, example: 'John Doe' },
      phone: { type: 'string', maxLength: 20, example: '+1234567890' },
      addressLine1: { type: 'string', maxLength: 200, example: '123 Main St' },
      addressLine2: { type: 'string', maxLength: 200 },
      city: { type: 'string', maxLength: 100, example: 'New York' },
      state: { type: 'string', maxLength: 100, example: 'NY' },
      country: { type: 'string', maxLength: 100, example: 'US' },
      postalCode: { type: 'string', maxLength: 20, example: '10001' },
      isDefault: { type: 'boolean' },
      deliveryInstructions: { type: 'string', maxLength: 500 },
    },
  },

  Notification: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      userId: { type: 'string' },
      type: { type: 'string', enum: ['ORDER', 'DELIVERY', 'PROMOTION', 'SYSTEM', 'SUPPORT', 'PAYMENT'] },
      title: { type: 'string', maxLength: 200, example: 'Order Confirmed' },
      body: { type: 'string', maxLength: 2000, example: 'Your order #ORD-001 has been confirmed.' },
      data: { type: 'object' },
      channels: { type: 'array', items: { type: 'string', enum: ['IN_APP', 'PUSH', 'EMAIL', 'SMS'] } },
      deliveryStatus: { type: 'string', enum: ['PENDING', 'SENT', 'DELIVERED', 'FAILED', 'READ'] },
      isRead: { type: 'boolean' },
      readAt: { type: 'string', format: 'date-time', nullable: true },
      sentAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
    },
    required: ['userId', 'type', 'title', 'body'],
  },

  SupportTicket: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      ticketNumber: { type: 'string', maxLength: 32, example: 'TKT-001' },
      userId: { type: 'string' },
      orderId: { type: 'string', nullable: true },
      category: { type: 'string', enum: ['ORDER', 'PAYMENT', 'DELIVERY', 'PRODUCT', 'ACCOUNT', 'OTHER'] },
      subject: { type: 'string', maxLength: 300, example: 'Wrong item received' },
      priority: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'URGENT'] },
      status: { type: 'string', enum: ['OPEN', 'IN_PROGRESS', 'WAITING_ON_CUSTOMER', 'RESOLVED', 'CLOSED'] },
      assignedTo: { type: 'string', nullable: true },
      messageCount: { type: 'integer', minimum: 0 },
      lastMessageAt: { type: 'string', format: 'date-time', nullable: true },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['ticketNumber', 'userId', 'category', 'subject'],
  },

  CreateSupportTicketDto: {
    type: 'object',
    required: ['category', 'subject', 'message'],
    properties: {
      orderId: { type: 'string' },
      category: { type: 'string', enum: ['ORDER', 'PAYMENT', 'DELIVERY', 'PRODUCT', 'ACCOUNT', 'OTHER'] },
      subject: { type: 'string', maxLength: 300, example: 'Wrong item received' },
      priority: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'URGENT'] },
      message: { type: 'string', maxLength: 10000, example: 'I received the wrong item in my order.' },
    },
  },

  AuditLog: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      entityType: { type: 'string', maxLength: 64, example: 'User' },
      entityId: { type: 'string' },
      action: { type: 'string', enum: ['CREATE', 'UPDATE', 'DELETE', 'SOFT_DELETE', 'RESTORE', 'LOGIN', 'LOGOUT', 'STATUS_CHANGE', 'PERMISSION_CHANGE'] },
      actorId: { type: 'string', nullable: true },
      actorRole: { type: 'string', maxLength: 32 },
      changes: {
        type: 'object',
        nullable: true,
        properties: {
          before: { type: 'object' },
          after: { type: 'object' },
        },
      },
      ipAddress: { type: 'string', maxLength: 45 },
      userAgent: { type: 'string', maxLength: 512 },
      requestId: { type: 'string', maxLength: 64 },
      metadata: { type: 'object' },
      createdAt: { type: 'string', format: 'date-time' },
    },
    required: ['entityType', 'entityId', 'action'],
  },

  Setting: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      key: { type: 'string', maxLength: 128, example: 'store.name' },
      value: { type: 'object' },
      group: { type: 'string', enum: ['GENERAL', 'PAYMENT', 'SHIPPING', 'NOTIFICATION', 'MOBILE', 'ANALYTICS', 'VENDOR', 'WAREHOUSE'] },
      description: { type: 'string', maxLength: 500 },
      isPublic: { type: 'boolean' },
      isEncrypted: { type: 'boolean' },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['key', 'value'],
  },

  CreateSettingDto: {
    type: 'object',
    required: ['key', 'value'],
    properties: {
      key: { type: 'string', maxLength: 128, pattern: '^[a-z][a-z0-9._-]*$', example: 'store.name' },
      value: { type: 'object' },
      group: { type: 'string', enum: ['GENERAL', 'PAYMENT', 'SHIPPING', 'NOTIFICATION', 'MOBILE', 'ANALYTICS', 'VENDOR', 'WAREHOUSE'] },
      description: { type: 'string', maxLength: 500 },
      isPublic: { type: 'boolean' },
      isEncrypted: { type: 'boolean' },
    },
  },

  UserDevice: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      userId: { type: 'string' },
      fcmToken: { type: 'string', example: 'fcm-token-xxx' },
      deviceType: { type: 'string', enum: ['android', 'web', 'ios'] },
      isActive: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['userId', 'fcmToken', 'deviceType'],
  },

  CreateUserDeviceDto: {
    type: 'object',
    required: ['fcmToken', 'deviceType'],
    properties: {
      fcmToken: { type: 'string', example: 'fcm-token-xxx' },
      deviceType: { type: 'string', enum: ['android', 'web', 'ios'], example: 'web' },
      isActive: { type: 'boolean' },
    },
  },

  WebUser: {
    type: 'object',
    properties: {
      _id: { type: 'string', description: 'Web user UUID' },
      email: { type: 'string', format: 'email', maxLength: 254, example: 'user@example.com' },
      firstName: { type: 'string', maxLength: 64, example: 'John' },
      lastName: { type: 'string', maxLength: 64, example: 'Doe' },
      avatar: { type: 'string', nullable: true },
      phone: { type: 'string', maxLength: 20, nullable: true },
      role: { type: 'string', enum: ['USER'], example: 'USER' },
      status: { type: 'string', enum: ['ACTIVE'], example: 'ACTIVE' },
      emailVerified: { type: 'boolean' },
      lastLoginAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['email', 'passwordHash', 'firstName', 'lastName'],
  },

  WebAuthResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      data: {
        type: 'object',
        properties: {
          user: { $ref: '#/components/schemas/WebUser' },
          token: { type: 'string', example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...' },
        },
        required: ['user', 'token'],
      },
    },
    required: ['success', 'data'],
  },

  WebUserProfile: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      email: { type: 'string', format: 'email', example: 'user@example.com' },
      firstName: { type: 'string', maxLength: 64, example: 'John' },
      lastName: { type: 'string', maxLength: 64, example: 'Doe' },
      avatar: { type: 'string', nullable: true },
      phone: { type: 'string', nullable: true },
      role: { type: 'string', enum: ['USER'] },
      status: { type: 'string', enum: ['ACTIVE'] },
      emailVerified: { type: 'boolean' },
      lastLoginAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
    },
    required: ['_id', 'email', 'firstName', 'lastName'],
  },

  AuthMessageResponse: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string', example: 'Logged out successfully' },
    },
    required: ['success', 'message'],
  },
};
